apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  labels:
    app: auth
spec:
  
  selector:
    matchLabels:
      app: auth
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: auth
    spec:
      serviceAccountName: auth-service
      containers:
        -  name: auth
           image: siba920429/instagram-on-aws:latest
           env:
            - name: PORT
              value: "4000"
            - name: ENVIRONMENT
              value: "dev"
            - name: API_VERSION
              value: "1"
            - name: ENVIRONMENT_REGION
              value: "us-east-1"
           ports:
            - containerPort: 4000
